project:
  type: website

website:
  title: "Raaghav's Blog"
  back-to-top-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/raagzz
      - icon: twitter
        href: https://twitter.com/raaghav03
      - icon: linkedin
        href: https://www.linkedin.com/in/raaghav-pohutezhini-1954b9225/

  page-footer: 
    left: "Copyright 2024, Raaghav P" 
    right: 
      - icon: github
        href: https://github.com/raagzz
      - icon: twitter 
        href: https://twitter.com/raaghav03

      

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

comments:
  giscus:
    repo: raagzz/raagzz.github.io

execute:
  freeze: auto